# Generated by Django 2.1.1 on 2019-11-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='processing', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'csv_file',
            },
        ),
        migrations.CreateModel(
            name='CsvRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(unique=True)),
                ('record_str', models.CharField(max_length=10000)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='csv_handler.CsvFile')),
            ],
            options={
                'db_table': 'csv_record',
            },
        ),
    ]
