# Generated by Django 2.1.1 on 2019-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecords',
            name='u_id',
            field=models.IntegerField(),
        ),
    ]
