# Generated by Django 2.1.1 on 2019-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0002_auto_20191115_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecords',
            name='u_id',
            field=models.CharField(max_length=100),
        ),
    ]
