# Generated by Django 2.1.1 on 2019-11-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0003_auto_20191115_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecords',
            name='u_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
