# Generated by Django 2.1.1 on 2019-11-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0004_auto_20191116_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='processed_records',
            field=models.IntegerField(default=0),
        ),
    ]
