# Generated by Django 2.1.1 on 2019-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0005_csvfile_processed_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvrecords',
            name='range',
            field=models.IntegerField(default=0),
        ),
    ]
