# Generated by Django 2.1.1 on 2019-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0006_csvrecords_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecords',
            name='u_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='csvrecords',
            unique_together={('u_id', 'file')},
        ),
    ]
