# Generated by Django 2.1.1 on 2019-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_handler', '0007_auto_20191116_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='fields_str',
            field=models.CharField(default='[]', max_length=10000),
            preserve_default=False,
        ),
    ]
